### ISSUE TITLE
Add Angular >= 5.x support. 

### ISSUE THREAD

**Issue by nybroe** [PioneerCode/pioneer-tree#34]
I am unable to import Pioneer-tree using angular 5.2.3.

### Expected behavior
When importing the module, I should get no errors.

### Actual behavior

Got following error when compiling:
"Module not found: Error: Can't resolve '@pioneer-code/pioneer-tree'"

### How to reproduce

1) Upgrade app to angular 5.2.3
2) Install latest version of Pioneer-tree
3) Upon node.js command prompt and start application using "npm start".

**Comment by chad-ramos** [comment]
Hi @nybroe 

Thanks for the filling this issue.  I am actually in the process of refactor the build system for this product so it utilizes the native ng-packagr tooling in the Angular CLI. Once this is done, the problem you are outlining should not be an issue anymore. 

Best,

Chad

**Comment by chad-ramos** [comment]
This is now being tracked at #35

**Comment by chad-ramos** [comment]
@nybroe Work has been completed and an RC has been published.  Of which is available at [npm](https://www.npmjs.com/package/@pioneer-code/pioneer-tree/v/2.0.0-rc.1).  Thank you for the feedback.

Best,

Chad
